name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        run: |
          ssh -v -o StrictHostKeyChecking=no sabyasachigolu@34.47.223.176 "echo 'SSH is working'"

      - name: Deploy to GCP VM
        run: |
          ssh -o StrictHostKeyChecking=no sabyasachigolu@34.47.223.176 << 'EOF'
            cd ~/Test/vite-project
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx
          EOF
