name: Deploy to GCP VM

on:
  push:
    branches:
      - main
  workflow_dispatch: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup GCP VM Access
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 34.47.223.176
          username: sabyasachigolu
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd ~/Test/vite-project
            git config --global credential.helper store
            echo "https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx
